services:
  - type: web
    name: nova-dev
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:0x1r/XCUeJUa8nu4hXBLMp1UewtNP85dfGKpfQoAs1c=
      - key: APP_URL
        value: https://nova-dev.onrender.com
